# general
seed: 42
workers: 0 # 0 for windows

dataset_dir: 'D:/datasets'
gpu_num: 0

# train options
batch_size: 32
image_size: 224
start_epoch: 1
epochs: 1
dataset: "ImageNet-10" # CIFAR-10 / CIFAR-100 / STL-10 / ImageNet-10 / ImageNet-dogs / tiny-ImageNet

# model options
resnet: "ResNet18" # ResNet18 / ResNet34 / ResNet50
feature_dim: 128
model_path: "save/ImageNet-10"
reload: False
forzen_backbone: False
confusion_matrix: False

# loss options
learning_rate: 0.0003 #0.0003
weight_decay:  0.
instance_temperature: 0.5
cluster_temperature: 1.0
