# general
seed: 42
workers: 8

dataset_dir: "~/dataset"
gpu_num: 1

# train options
batch_size: 64
image_size: 224
start_epoch: 0
epochs: 500
dataset: "ImageNet-dogs" # CIFAR-10 / CIFAR-100 / STL-10 / ImageNet-10 / ImageNet-dogs / tiny-ImageNet

# model options
resnet: "ResNet34" # ResNet18 / ResNet34 / ResNet50
feature_dim: 128
model_path: "save/backbone/RN50/ImageNet-dogs"
reload: False
forzen_backbone: False
confusion_matrix: False

# loss options
learning_rate: 0.0003 #0.0003
weight_decay:  0.
instance_temperature: 0.5
cluster_temperature: 1.0
